<?php
/**
 * Created by PhpStorm.
 * User: eVol
 * Date: 06.12.2017
 * Time: 12:24
 */

namespace app\controllers;
use Yii;
use app\models\TestForm;

class PostController extends AppController
{

    public $layout = 'basic';

    public function beforeAction($action)
    {
//        debug($action);
        if ($action->id == 'index'){
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){


        $model = new TestForm();
        if($model->load(Yii::$app->request->post())) {
//            debug(Yii::$app->request->post());
//            debug($model);
//            die;
            if ($model->validate()){
                Yii::$app->session->setFlash('success', 'Данные приняты');
                return $this->refresh();
            } else {
                Yii::$app->session->setFlash('error', 'Ошибка');
            }
        }


        if(Yii::$app->request->isAjax) {
//            debug($_POST);
            debug(Yii::$app->request->post());
            return 'test';

        }
//        $names = ['Ivanov', 'Petrov', 'Sidorov'];

//        var_dump(Yii::$app);
//        $this->debug(Yii::$app);
//        $this->debug($names);
//        return $this->render('test');
        return $this->render('test', compact('model'));
    }
    public function actionShow(){
//        $this->layout = 'basic';
        $this->view->title = "Одна статья";
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'ключевики']);
        $this->view->registerMetaTag(['name' => 'description', 'content' => 'описание']);
        return $this->render('show');
    }
}