<?php
/**
 * Created by PhpStorm.
 * User: eVol
 * Date: 06.12.2017
 * Time: 12:24
 */

namespace app\controllers;
use Yii;

class PostController extends AppController
{

    public $layout = 'basic';

    public function beforeAction($action)
    {
//        debug($action);
        if ($action->id == 'index'){
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
        if(Yii::$app->request->isAjax) {
//            debug($_POST);
            debug(Yii::$app->request->post());
            return 'test';

        }
//        $names = ['Ivanov', 'Petrov', 'Sidorov'];

//        var_dump(Yii::$app);
//        $this->debug(Yii::$app);
//        $this->debug($names);
        return $this->render('test');
    }
    public function actionShow(){
//        $this->layout = 'basic';
        return $this->render('show');
    }
}