<?php
/**
 * Created by PhpStorm.
 * User: eVol
 * Date: 07.12.2017
 * Time: 15:07
 */

namespace app\models;
use yii\base\Model;

class TestForm extends Model
{
    public $name;
    public $email;
    public $text;

    public function attributeLabels()
    {
        return [
            'name' => 'Имя',
            'email' => 'E-mail',
            'text' => 'Текст сообщения'
        ];
        //return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }
    public function  rules()
    {
        return [
//            [['name', 'email'], 'required', 'message' => 'Поле обязательно'],
            [['name', 'email'], 'required'],
            ['email', 'email'],
//            ['name', 'string','min' => 2],
//            ['name', 'string','max' => 5]
            ['name', 'string','length' => [2,5]],
            ['name', 'myRule'],
            ['text', 'trim']
        ];
    }
    public function myRule($attrs) {
        if(!in_array($this->$attrs, ['hello', 'world'])){
            $this->addError($attrs, "Wrong!");
        }
    }
}